---
services:
  db:
    image: registry.redhat.io/rhel9/postgresql-15
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USER=dashdotdb
      - POSTGRESQL_DATABASE=dashdotdb
    networks:
    - dashdotdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashdotdb -d dashdotdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
    - dashdotdb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DASHDOTDB_DATABASE_URL=postgresql://dashdotdb:postgres@db:5432/dashdotdb
    ports:
      - 8080:8080
    restart: always

networks:
  dashdotdb:
