---
version: "3.9"
services:
  db:
    container_name: dashdot-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  app:
    stdin_open: true
    tty: true
    links:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DASHDOTDB_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - 8080:8080
