---
services:
  db:
    image: registry.redhat.io/rhel9/postgresql-15
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USER=dashdotdb
      - POSTGRESQL_DATABASE=dashdotdb
    networks:
    - dashdotdb

  app:
    container_name: ${WEB_CONTAINER_NAME}
    networks:
    - dashdotdb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DASHDOTDB_DATABASE_URL=postgresql://dashdotdb:postgres@db:5432/dashdotdb
    ports:
      - 8080
    restart: always

networks:
  dashdotdb:
