{
 "title": "DashdotDB CSO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(imagemanifestvuln_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(imagemanifestvuln_total, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Critical Vulnerabilities (sum over all pods in namespace)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(imagemanifestvuln_total{exported_namespace=\"$namespace\", cluster=\"$cluster\", severity=\"Critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total High Vulnerabilities (sum over all pods in namespace)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(imagemanifestvuln_total{exported_namespace=\"$namespace\", cluster=\"$cluster\", severity=\"High\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Critical Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "imagemanifestvuln_total{cluster=\"$cluster\", exported_namespace=\"$namespace\", severity=\"Critical\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "High Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "High Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "imagemanifestvuln_total{cluster=\"$cluster\", exported_namespace=\"$namespace\", severity=\"High\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}