"""empty message

Revision ID: 0222e3143aaf
Revises: 3f43e3d39346
Create Date: 2021-03-22 15:10:50.099981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0222e3143aaf'
down_revision = '3f43e3d39346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('serviceslo_cluster_id_fkey', 'serviceslo', type_='foreignkey')
    op.drop_column('serviceslo', 'cluster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceslo', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('serviceslo_cluster_id_fkey', 'serviceslo', 'cluster', ['cluster_id'], ['id'])
    # ### end Alembic commands ###
