"""empty message

Revision ID: 248a30ecba33
Revises: 9d64fd56c7e4
Create Date: 2023-01-12 12:34:30.398192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248a30ecba33'
down_revision = '9d64fd56c7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podimage',
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['pod_id'], ['pod.id'], ),
    sa.PrimaryKeyConstraint('pod_id', 'image_id')
    )
    op.drop_index('ix_pod_image_id', table_name='pod')
    op.drop_constraint('pod_image_id_fkey', 'pod', type_='foreignkey')
    op.drop_column('pod', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pod_image_id_fkey', 'pod', 'image', ['image_id'], ['id'])
    op.create_index('ix_pod_image_id', 'pod', ['image_id'], unique=False)
    op.drop_table('podimage')
    # ### end Alembic commands ###
