"""remove status field

Revision ID: 2dde25241edc
Revises: f2ced20babab
Create Date: 2020-10-22 04:25:15.576898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dde25241edc'
down_revision = 'f2ced20babab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploymentvalidation', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploymentvalidation', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
