"""empty message

Revision ID: 30a829d79e7f
Revises: 902915d89c64
Create Date: 2021-10-13 18:20:02.694048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a829d79e7f'
down_revision = '902915d89c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slodoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slodoc_name'), 'slodoc', ['name'], unique=True)
    op.add_column('serviceslo', sa.Column('slodoc_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_serviceslo_slodoc_id'), 'serviceslo', ['slodoc_id'], unique=False)
    op.create_foreign_key(None, 'serviceslo', 'slodoc', ['slodoc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serviceslo', type_='foreignkey')
    op.drop_index(op.f('ix_serviceslo_slodoc_id'), table_name='serviceslo')
    op.drop_column('serviceslo', 'slodoc_id')
    op.drop_index(op.f('ix_slodoc_name'), table_name='slodoc')
    op.drop_table('slodoc')
    # ### end Alembic commands ###
