"""empty message

Revision ID: 6d6661369d50
Revises: 248a30ecba33
Create Date: 2023-09-04 12:43:40.731381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6661369d50'
down_revision = '248a30ecba33'
branch_labels = None
depends_on = None

table_name = 'token'
column_name = 'data_type'
enum_name = 'datatypes'
tmp_enum_name = 'tmp_' + enum_name

old_options = ('CSODataType', 'DVODataType', 'SLODataType')
new_options = sorted(old_options + ('DORADataType',))

old_type = sa.Enum(*old_options, name=enum_name)
new_type = sa.Enum(*new_options, name=enum_name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doradeployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=256), nullable=True),
    sa.Column('finish_timestamp', sa.DateTime(), nullable=True),
    sa.Column('app_name', sa.String(length=256), nullable=True),
    sa.Column('env_name', sa.String(length=256), nullable=True),
    sa.Column('pipeline', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name', 'env_name', 'pipeline', 'trigger_reason', name='doradeployment_trigger_reason_app_name_env_name_pipeline_uc')
    )
    op.create_index(op.f('ix_doradeployment_app_name'), 'doradeployment', ['app_name'], unique=False)
    op.create_index(op.f('ix_doradeployment_env_name'), 'doradeployment', ['env_name'], unique=False)
    op.create_index(op.f('ix_doradeployment_finish_timestamp'), 'doradeployment', ['finish_timestamp'], unique=False)
    op.create_index(op.f('ix_doradeployment_pipeline'), 'doradeployment', ['pipeline'], unique=False)
    op.create_index(op.f('ix_doradeployment_token_id'), 'doradeployment', ['token_id'], unique=False)
    op.create_index(op.f('ix_doradeployment_trigger_reason'), 'doradeployment', ['trigger_reason'], unique=False)
    op.create_table('doracommit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('revision', sa.String(length=40), nullable=True),
    sa.Column('repo', sa.String(length=256), nullable=True),
    sa.Column('lttc', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['doradeployment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'revision', 'repo', name='doracommit_depid_rev_repo_uc')
    )
    op.create_index(op.f('ix_doracommit_deployment_id'), 'doracommit', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_doracommit_timestamp'), 'doracommit', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    # Manually added to add a new type to datatypes
    # op.execute("ALTER TYPE " + enum_name + " ADD VALUE 'DORADataType'")
    op.execute("ALTER TYPE " + enum_name + " RENAME TO " + tmp_enum_name)
    new_type.create(op.get_bind())
    op.execute("ALTER TABLE " + table_name + " ALTER COLUMN " + column_name +
               " TYPE " + enum_name + " USING " + table_name + "::text::" +
               enum_name)
    op.execute("DROP TYPE " + tmp_enum_name)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doracommit_timestamp'), table_name='doracommit')
    op.drop_index(op.f('ix_doracommit_deployment_id'), table_name='doracommit')
    op.drop_table('doracommit')
    op.drop_index(op.f('ix_doradeployment_trigger_reason'), table_name='doradeployment')
    op.drop_index(op.f('ix_doradeployment_token_id'), table_name='doradeployment')
    op.drop_index(op.f('ix_doradeployment_pipeline'), table_name='doradeployment')
    op.drop_index(op.f('ix_doradeployment_finish_timestamp'), table_name='doradeployment')
    op.drop_index(op.f('ix_doradeployment_env_name'), table_name='doradeployment')
    op.drop_index(op.f('ix_doradeployment_app_name'), table_name='doradeployment')
    op.drop_table('doradeployment')
    # ### end Alembic commands ###

    # TODO: removing DORADataType. The following code doesn't work
    # enum_type = sa.Enum('CSODataType', 'DVODataType', 'SLODataType', name='datatypes')
    # op.execute('ALTER TYPE datatypes RENAME TO datatypes_old')
    # enum_type.create(op.get_bind())
    # op.alter_column(
    #     table_name='token',
    #     column_name='data_type',
    #     nullable=True,
    #     type_=enum_type,
    #     postgresql_using='data_type::datatypes'
    # )
    # op.execute('DROP TYPE datatypes_old')
    #
    # Gives this error:
    # ERROR:  cannot cast type datatypes_old to datatypes

    # @REF [Creating migrations when changing an enum in Python using SQLAlchemy](https://markrailton.com/blog/creating-migrations-when-changing-an-enum-in-python-using-sql-alchemy)
    # Instatiate db query
    audit = sa.sql.table('token', sa.Column('data_type', new_type,
                                            nullable=False))
    # Rename
    op.execute("ALTER TYPE " + enum_name + " RENAME TO " + tmp_enum_name)
    old_type.create(op.get_bind())
    op.execute("ALTER TABLE token ALTER COLUMN data_type TYPE " + enum_name +
               " USING " + table_name + "::text::" + enum_name)

    # Drop
    op.execute("DROP TYPE " + tmp_enum_name)
