"""empty message

Revision ID: 7381c6e36b95
Revises: 0222e3143aaf
Create Date: 2021-07-19 13:25:09.822068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381c6e36b95'
down_revision = '0222e3143aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('data_type', sa.Enum('CSODataType', 'DVODataType', 'SLODataType', name='datatypes'), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('latesttokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deploymentvalidation', sa.Column('tokens_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deploymentvalidation', 'tokens', ['tokens_id'], ['id'])
    op.add_column('pod', sa.Column('tokens_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pod', 'tokens', ['tokens_id'], ['id'])
    op.add_column('serviceslo', sa.Column('tokens_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'serviceslo', 'tokens', ['tokens_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serviceslo', type_='foreignkey')
    op.drop_column('serviceslo', 'tokens_id')
    op.drop_constraint(None, 'pod', type_='foreignkey')
    op.drop_column('pod', 'tokens_id')
    op.drop_constraint(None, 'deploymentvalidation', type_='foreignkey')
    op.drop_column('deploymentvalidation', 'tokens_id')
    op.drop_table('latesttokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
