"""empty message

Revision ID: 8877339046ad
Revises: eab8950ce577
Create Date: 2021-08-05 14:33:17.330232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8877339046ad'
down_revision = 'eab8950ce577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='serviceslo',
        column_name='value',
        nullable=False,
        type_=sa.Float()
    )

    op.alter_column(
        table_name='serviceslo',
        column_name='target',
        nullable=False,
        type_=sa.Float()
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='serviceslo',
        column_name='value',
        nullable=False,
        type_=sa.Integer()
    )

    op.alter_column(
        table_name='serviceslo',
        column_name='target',
        nullable=False,
        type_=sa.Integer()
    )
    # ### end Alembic commands ###
