"""empty message

Revision ID: 902915d89c64
Revises: 9c04fbe05080
Create Date: 2021-08-27 10:56:34.010222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '902915d89c64'
down_revision = '9c04fbe05080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vulnerability_name'), 'vulnerability', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_name'), table_name='vulnerability')
    # ### end Alembic commands ###
