"""empty message

Revision ID: 963bd51e139c
Revises: 30a829d79e7f
Create Date: 2023-01-06 10:15:09.472580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963bd51e139c'
down_revision = '30a829d79e7f'
branch_labels = None
depends_on = None


def upgrade():
    # Alembic does not alter the varchar(10000) change - need to do this manually here
    op.execute('ALTER TABLE vulnerability ALTER COLUMN name TYPE varchar(512);')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_name_namespacename_version_versionformat', table_name='feature')
    op.create_index('ix_feature_name_version', 'feature', ['name', 'version'], unique=False)
    op.drop_column('feature', 'versionformat')
    op.drop_column('feature', 'namespacename')
    op.add_column('vulnerability', sa.Column('namespacename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # Alembic does not alter the varchar(64) change - need to do this manually here
    op.execute('ALTER TABLE vulnerability ALTER COLUMN name TYPE varchar(64);')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability', 'namespacename')
    op.add_column('feature', sa.Column('namespacename', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('feature', sa.Column('versionformat', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index('ix_feature_name_version', table_name='feature')
    op.create_index('ix_feature_name_namespacename_version_versionformat', 'feature', ['name', 'namespacename', 'version', 'versionformat'], unique=False)
    # ### end Alembic commands ###
