"""empty message

Revision ID: 9c04fbe05080
Revises: 8877339046ad
Create Date: 2021-08-26 17:39:57.279251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c04fbe05080'
down_revision = '8877339046ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deploymentvalidation_name'), 'deploymentvalidation', ['name'], unique=False)
    op.create_index(op.f('ix_deploymentvalidation_namespace_id'), 'deploymentvalidation', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_deploymentvalidation_token_id'), 'deploymentvalidation', ['token_id'], unique=False)
    op.create_index(op.f('ix_deploymentvalidation_validation_id'), 'deploymentvalidation', ['validation_id'], unique=False)
    op.create_index('ix_feature_name_namespacename_version_versionformat', 'feature', ['name', 'namespacename', 'version', 'versionformat'], unique=False)
    op.create_index('ix_image_name_manifest', 'image', ['name', 'manifest'], unique=False)
    op.create_index(op.f('ix_namespace_cluster_id'), 'namespace', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_namespace_name'), 'namespace', ['name'], unique=False)
    op.create_unique_constraint(None, 'objectkind', ['name'])
    op.create_index(op.f('ix_pod_image_id'), 'pod', ['image_id'], unique=False)
    op.create_index(op.f('ix_pod_name'), 'pod', ['name'], unique=False)
    op.create_index(op.f('ix_pod_namespace_id'), 'pod', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_pod_token_id'), 'pod', ['token_id'], unique=False)
    op.create_index(op.f('ix_serviceslo_name'), 'serviceslo', ['name'], unique=False)
    op.create_index(op.f('ix_serviceslo_namespace_id'), 'serviceslo', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_serviceslo_service_id'), 'serviceslo', ['service_id'], unique=False)
    op.create_index(op.f('ix_serviceslo_token_id'), 'serviceslo', ['token_id'], unique=False)
    op.create_index(op.f('ix_token_uuid'), 'token', ['uuid'], unique=False)
    op.create_index(op.f('ix_vulnerability_feature_id'), 'vulnerability', ['feature_id'], unique=False)
    op.create_index('ix_vulnerability_name_description_fixedby_link', 'vulnerability', ['name', 'description', 'fixedby', 'link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vulnerability_name_description_fixedby_link', table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_feature_id'), table_name='vulnerability')
    op.drop_index(op.f('ix_token_uuid'), table_name='token')
    op.drop_index(op.f('ix_serviceslo_token_id'), table_name='serviceslo')
    op.drop_index(op.f('ix_serviceslo_service_id'), table_name='serviceslo')
    op.drop_index(op.f('ix_serviceslo_namespace_id'), table_name='serviceslo')
    op.drop_index(op.f('ix_serviceslo_name'), table_name='serviceslo')
    op.drop_index(op.f('ix_pod_token_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_namespace_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_name'), table_name='pod')
    op.drop_index(op.f('ix_pod_image_id'), table_name='pod')
    op.drop_constraint(None, 'objectkind', type_='unique')
    op.drop_index(op.f('ix_namespace_name'), table_name='namespace')
    op.drop_index(op.f('ix_namespace_cluster_id'), table_name='namespace')
    op.drop_index('ix_image_name_manifest', table_name='image')
    op.drop_index('ix_feature_name_namespacename_version_versionformat', table_name='feature')
    op.drop_index(op.f('ix_deploymentvalidation_validation_id'), table_name='deploymentvalidation')
    op.drop_index(op.f('ix_deploymentvalidation_token_id'), table_name='deploymentvalidation')
    op.drop_index(op.f('ix_deploymentvalidation_namespace_id'), table_name='deploymentvalidation')
    op.drop_index(op.f('ix_deploymentvalidation_name'), table_name='deploymentvalidation')
    # ### end Alembic commands ###
