"""empty message

Revision ID: b22e5138a938
Revises: e6210176f55c
Create Date: 2020-10-29 13:52:55.784625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22e5138a938'
down_revision = 'e6210176f55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectkind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploymentvalidation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('objectkind_id', sa.Integer(), nullable=True),
    sa.Column('validation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ),
    sa.ForeignKeyConstraint(['objectkind_id'], ['objectkind.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['validation_id'], ['validation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploymentvalidation')
    op.drop_table('validation')
    op.drop_table('objectkind')
    # ### end Alembic commands ###
