"""Initial migration.

Revision ID: c4f641d56546
Revises: 
Create Date: 2020-05-28 15:36:22.816733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f641d56546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_name'), 'cluster', ['name'], unique=True)
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('namespacename', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('versionformat', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_name'), 'feature', ['name'], unique=False)
    op.create_index(op.f('ix_feature_namespacename'), 'feature', ['namespacename'], unique=False)
    op.create_index(op.f('ix_feature_version'), 'feature', ['version'], unique=False)
    op.create_index(op.f('ix_feature_versionformat'), 'feature', ['versionformat'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('manifest', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_manifest'), 'image', ['manifest'], unique=False)
    op.create_index(op.f('ix_image_name'), 'image', ['name'], unique=False)
    op.create_table('severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_severity_name'), 'severity', ['name'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagefeature',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'feature_id')
    )
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespace_name'), 'namespace', ['name'], unique=False)
    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('fixedby', sa.String(length=10000), nullable=True),
    sa.Column('link', sa.String(length=10000), nullable=True),
    sa.Column('severity_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['severity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_description'), 'vulnerability', ['description'], unique=False)
    op.create_index(op.f('ix_vulnerability_fixedby'), 'vulnerability', ['fixedby'], unique=False)
    op.create_index(op.f('ix_vulnerability_link'), 'vulnerability', ['link'], unique=False)
    op.create_index(op.f('ix_vulnerability_name'), 'vulnerability', ['name'], unique=False)
    op.create_table('pod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_name'), 'pod', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pod_name'), table_name='pod')
    op.drop_table('pod')
    op.drop_index(op.f('ix_vulnerability_name'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_link'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_fixedby'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_description'), table_name='vulnerability')
    op.drop_table('vulnerability')
    op.drop_index(op.f('ix_namespace_name'), table_name='namespace')
    op.drop_table('namespace')
    op.drop_table('imagefeature')
    op.drop_table('token')
    op.drop_index(op.f('ix_severity_name'), table_name='severity')
    op.drop_table('severity')
    op.drop_index(op.f('ix_image_name'), table_name='image')
    op.drop_index(op.f('ix_image_manifest'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_feature_versionformat'), table_name='feature')
    op.drop_index(op.f('ix_feature_version'), table_name='feature')
    op.drop_index(op.f('ix_feature_namespacename'), table_name='feature')
    op.drop_index(op.f('ix_feature_name'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_cluster_name'), table_name='cluster')
    op.drop_table('cluster')
    # ### end Alembic commands ###
