"""empty message

Revision ID: e6210176f55c
Revises: c4f641d56546
Create Date: 2020-07-14 10:00:02.318230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6210176f55c'
down_revision = 'c4f641d56546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_name', table_name='cluster')
    op.create_unique_constraint(None, 'cluster', ['name'])
    op.drop_index('ix_feature_name', table_name='feature')
    op.drop_index('ix_feature_namespacename', table_name='feature')
    op.drop_index('ix_feature_version', table_name='feature')
    op.drop_index('ix_feature_versionformat', table_name='feature')
    op.drop_index('ix_image_manifest', table_name='image')
    op.drop_index('ix_image_name', table_name='image')
    op.drop_index('ix_namespace_name', table_name='namespace')
    op.drop_index('ix_pod_name', table_name='pod')
    op.drop_index('ix_severity_name', table_name='severity')
    op.create_unique_constraint(None, 'severity', ['name'])
    op.drop_index('ix_vulnerability_description', table_name='vulnerability')
    op.drop_index('ix_vulnerability_fixedby', table_name='vulnerability')
    op.drop_index('ix_vulnerability_link', table_name='vulnerability')
    op.drop_index('ix_vulnerability_name', table_name='vulnerability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vulnerability_name', 'vulnerability', ['name'], unique=False)
    op.create_index('ix_vulnerability_link', 'vulnerability', ['link'], unique=False)
    op.create_index('ix_vulnerability_fixedby', 'vulnerability', ['fixedby'], unique=False)
    op.create_index('ix_vulnerability_description', 'vulnerability', ['description'], unique=False)
    op.drop_constraint(None, 'severity', type_='unique')
    op.create_index('ix_severity_name', 'severity', ['name'], unique=True)
    op.create_index('ix_pod_name', 'pod', ['name'], unique=False)
    op.create_index('ix_namespace_name', 'namespace', ['name'], unique=False)
    op.create_index('ix_image_name', 'image', ['name'], unique=False)
    op.create_index('ix_image_manifest', 'image', ['manifest'], unique=False)
    op.create_index('ix_feature_versionformat', 'feature', ['versionformat'], unique=False)
    op.create_index('ix_feature_version', 'feature', ['version'], unique=False)
    op.create_index('ix_feature_namespacename', 'feature', ['namespacename'], unique=False)
    op.create_index('ix_feature_name', 'feature', ['name'], unique=False)
    op.drop_constraint(None, 'cluster', type_='unique')
    op.create_index('ix_cluster_name', 'cluster', ['name'], unique=True)
    # ### end Alembic commands ###
