"""empty message

Revision ID: eab8950ce577
Revises: 0222e3143aaf
Create Date: 2021-07-20 12:18:49.708026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab8950ce577'
down_revision = '0222e3143aaf'
branch_labels = None
depends_on = None


# Creation of the Enum type has to be done manually with Alembic
enum_name = 'datatypes'
options = ('CSODataType', 'DVODataType', 'SLODataType')
enum_type = sa.Enum(*options, name=enum_name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latesttokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Manually added to create the Enum
    enum_type.create(op.get_bind())
    op.add_column('token', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('token', sa.Column('data_type', sa.Enum('CSODataType', 'DVODataType', 'SLODataType', name='datatypes'), nullable=True))
    op.add_column('token', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'is_open')
    op.drop_column('token', 'data_type')
    op.drop_column('token', 'uuid')
    op.drop_table('latesttokens')
    # Manually added to delete the enum type
    op.execute('DROP TYPE ' + enum_name)
    # ### end Alembic commands ###
